##
## Makefile<games> for  in /home/tomlenor/Documents/Tek2/cpp_arcade/games
##
## Made by tomlenor
## Login   <tom.lenormand@epitech.eu>
##
## Started on  Mon Mar 20 12:08:11 2017 tomlenor
## Last update Sun Apr  9 03:29:08 2017 Erwan
##

GAME1	=	snake

GAME2	=	pacman

all:
	cd $(GAME1)/ ; make
	cd $(GAME2)/ ; make

clean:
	cd $(GAME1)/ ; make clean
	cd $(GAME2)/ ; make clean

fclean:
	cd $(GAME1)/ ; make fclean
	cd $(GAME2)/ ; make fclean

re: fclean all
