##
## Makefile for arcade in /home/erwan/Tek2/C++/cpp_arcade/lib
##
## Made by Erwan
## Login   <erwan.guiomar@epitech.eu>
##
## Started on  Thu Mar 23 16:05:33 2017 Erwan
## Last update Sat Apr  8 11:22:23 2017 Erwan
##

GFXDIR1	= Lapin

GFXDIR2	= SDL

GFXDIR3	= ncurse

all:
	cd $(GFXDIR1)/; make
	cd $(GFXDIR2)/; make
	cd $(GFXDIR3)/; make

clean:
	cd $(GFXDIR1)/; make clean
	cd $(GFXDIR2)/; make clean
	cd $(GFXDIR3)/; make clean

fclean:
	cd $(GFXDIR1)/; make fclean
	cd $(GFXDIR2)/; make fclean
	cd $(GFXDIR3)/; make fclean

re: fclean all
